// Oakland Zoo Trading Cards database.
// Sourced from the official checklist published at oaklandzoo.org/cards
// (TradingCards_CheckList PDF) and the trading card library pages, cross-referenced
// against oaklandzoo.org/trading-card-category/* archive pages for card numbers and
// photos. New cards rotate monthly at the zoo, so this list can be edited below as
// new sets are announced. Cards without a confirmed `number` or `image` were not
// found on the site at time of writing (e.g. the Boo at the Zoo, Oakland Roots &
// Soul, and ZooCamp special editions have no dedicated category page).

const OAKLAND_ZOO_CARD_SETS = [
  {
    id: "standard",
    name: "Standard Cards",
    description: "The core 100-card set found year-round at Keeper Talks and around the Zoo.",
    cards: [
      { name: "Gray Wolf", number: 1, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Gray-Wolf-Unavailable.webp" },
      { name: "Aldabra Tortoise", number: 2, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Aldabra-Tortoise-Unavailable.webp" },
      { name: "African Elephant", number: 3, image: "https://www.oaklandzoo.org/app/uploads/2026/02/African-Elephant-Unavailable.webp" },
      { name: "Malayan Wreathed Hornbill", number: 4, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Hornbill-Unavailable.webp" },
      { name: "Grizzly Bear", number: 5, image: "https://www.oaklandzoo.org/app/uploads/2026/02/5-of-100-Grizzly-Bear.webp" },
      { name: "Meerkat", number: 6, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Meerkat-Unavailable.webp" },
      { name: "Ring-Tailed Lemur", number: 7, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Ring-Tailed-Lemur-Unavailable.webp" },
      { name: "Tiger", number: 8, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Tiger-Unavailable.webp" },
      { name: "Mountain Lion", number: 9, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Mountain-Lion-Unavailable.webp" },
      { name: "Great Curassow", number: 10, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Great-Curassow-Unavailable.webp" },
      { name: "American Alligator", number: 11, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Alligator-Unavailable.webp" },
      { name: "Chimpanzee", number: 12, image: "https://www.oaklandzoo.org/app/uploads/2026/03/12-of-100-Chimpanzee.webp" },
      { name: "Reticulated Giraffe", number: 13, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Giraffe-Unavailable.webp" },
      { name: "American Bison", number: 14, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Bison-Unavailable.webp" },
      { name: "Giant African Millipede", number: 15, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Millipede-Unavailable.webp" },
      { name: "Ball (Royal) Python", number: 16 },
      { name: "White-Handed (Lar) Gibbon", number: 17, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Gibbon-Unavailable.webp" },
      { name: "California Condor", number: 18, image: "https://www.oaklandzoo.org/app/uploads/2026/03/18-of-100-Condor.webp" },
      { name: "North American River Otter", number: 19, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Otter-Unavailable.webp" },
      { name: "Spotted Hyena", number: 20, image: "https://www.oaklandzoo.org/app/uploads/2026/03/20-of-100-Hyena.webp" },
      { name: "Malayan Flying Fox", number: 21, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Malayan-Flying-Fox-Unavailable.webp" },
      { name: "Southern Pudu", number: 22, image: "https://www.oaklandzoo.org/app/uploads/2026/03/22-of-100-Pudu.webp" },
      { name: "Superb Starling", number: 23, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Starling-Unavailable.webp" },
      { name: "Leaf-Cutter Ant", number: 24, image: "https://www.oaklandzoo.org/app/uploads/2026/02/24-of-100-Leaf-Cutter-Ant.webp" },
      { name: "Jaguar", number: 25, image: "https://www.oaklandzoo.org/app/uploads/2026/02/25-of-100-Jaguar.webp" },
      { name: "Colorado River Toad", number: 26, image: "https://www.oaklandzoo.org/app/uploads/2026/02/26-of-100-Colorado-River-Toad.webp" },
      { name: "Common Wallaroo", number: 27, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Wallaroo-Unavailable.webp" },
      { name: "Klipspringer", number: 28, image: "https://www.oaklandzoo.org/app/uploads/2026/02/Klipspringer-Unavailable.webp" },
      { name: "Cotton-Top Tamarin", number: 29, image: "https://www.oaklandzoo.org/app/uploads/2026/03/29-of-100-Tamarin.webp" },
      { name: "Gila Monster", number: 30, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Gila-Monster-Unavailable.webp" },
      { name: "Yellow-Billed Stork", number: 31, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Stork-Unavailable.webp" },
      { name: "Bald Eagle", number: 32, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Bald-Eagle-Unavailable.webp" },
      { name: "Nigerian Dwarf Goat", number: 33, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Nigerian-Dwarf-Goat-Unavailable.webp" },
      { name: "Grant's Zebra", number: 34, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Zebra-Unavailable.webp" },
      { name: "Sun Bear", number: 35, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Sun-Bear-Unavailable.webp" },
      { name: "Green Mantella Frog", number: 36, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Green-Mantella-Unavailable.webp" },
      { name: "Schmidt's Red-Tailed Monkey", number: 37, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Red-Tailed-Monkey-Unavailable.webp" },
      { name: "Lilac-Crowned Amazon", number: 38, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Lilac-Crowned-Amazon-Unavailable.webp" },
      { name: "New Guinea Walking Stick", number: 39, image: "https://www.oaklandzoo.org/app/uploads/2026/03/New-Guinea-Walking-Stick-Unavailable.webp" },
      { name: "Red-Tailed Hawk", number: 40, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Hawk-Unavailable.webp" },
      { name: "Eastern Box Turtle", number: 41, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Eastern-Box-Turtle-Unavailable.webp" },
      { name: "Hamerkop", number: 42, image: "https://www.oaklandzoo.org/app/uploads/2026/03/42-of-100-Hamerkop.webp" },
      { name: "Red-Rumped Agouti", number: 43, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Agouti-Unavailable.webp" },
      { name: "Black Tree Monitor", number: 44, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Black-Tree-Monitor-Unavailable.webp" },
      { name: "Guira Cuckoo", number: 45, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Guira-Cuckoo-Unavailable.webp" },
      { name: "Madagascar Hissing Cockroach", number: 46, image: "https://www.oaklandzoo.org/app/uploads/2026/03/46-of-100-Madagascar-Hissing-Cockroach.webp" },
      { name: "Dromedary Camel", number: 47, image: "https://www.oaklandzoo.org/app/uploads/2026/03/47-of-100-Dromedary-Camel.webp" },
      { name: "Amazon Milk Tree Frog", number: 48, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Amazon-Milky-Frog-Unavailable.webp" },
      { name: "Blue and Gold Macaw", number: 49, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Blue-and-Gold-Macaw-Unavailable-1.webp" },
      { name: "Pancake Tortoise", number: 50, image: "https://www.oaklandzoo.org/app/uploads/2026/03/50-of-100-Pancake-Tortoise.webp" },
      { name: "Guinea Forest Hog", number: 51, image: "https://www.oaklandzoo.org/app/uploads/2026/03/51-of-100-Guinea-Forest-Hog.webp" },
      { name: "Egyptian Goose", number: 52, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Egyptian-Goose-Unavailable.webp" },
      { name: "Squirrel Monkey", number: 53, image: "https://www.oaklandzoo.org/app/uploads/2026/03/53-of-100-Squirrel-Monkey.webp" },
      { name: "Amazon Tree Boa", number: 54, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Amazon-Tree-Boa-Unavailable.webp" },
      { name: "Pied Crow", number: 55, image: "https://www.oaklandzoo.org/app/uploads/2026/03/55-of-100-Pied-Crow.webp" },
      { name: "Western Pond Turtle", number: 56, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Western-Pond-Turtle-Unavailable.webp" },
      { name: "Hadada Ibis", number: 57, image: "https://www.oaklandzoo.org/app/uploads/2026/03/57-of-100-Hadada-Ibis.webp" },
      { name: "Crowned Lemur", number: 58, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Crowned-Lemur-Female-Unavailable.webp" },
      { name: "Black-Throated Monitor", number: 59, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Black-Throated-Monitor-Unavailable.webp" },
      { name: "Malaysian Dead Leaf Mantis", number: 60, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Dead-Leaf-Mantis-Unavailable.webp" },
      { name: "Siamang", number: 61, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Siamang-Unavailable.webp" },
      { name: "African Spurred Tortoise", number: 62, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Spurred-Tortoise-Unavailable.webp" },
      { name: "Hooded Vulture", number: 63, image: "https://www.oaklandzoo.org/app/uploads/2026/03/63-of-100-Hooded-Vulture.webp" },
      { name: "Henkel's Leaf-Tailed Gecko", number: 64, image: "https://www.oaklandzoo.org/app/uploads/2026/03/64-of-100-Leaf-Tailed-Gecko.webp" },
      { name: "Emu", number: 65, image: "https://www.oaklandzoo.org/app/uploads/2026/03/65-of-100-Emu.webp" },
      { name: "Warthog", number: 66, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Warthog-Unavailable.webp" },
      { name: "Black Widow", number: 67, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Black-Widow-Unavailable.webp" },
      { name: "Military Macaw", number: 68, image: "https://www.oaklandzoo.org/app/uploads/2026/03/68-of-100-Military-Macaw.webp" },
      { name: "Shetland Sheep", number: 69, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Shetland-Sheep-Unavailable.webp" },
      { name: "White-Faced Whistling Duck", number: 70, image: "https://www.oaklandzoo.org/app/uploads/2026/03/White-Faced-Whistling-Duck-Unavailable.webp" },
      { name: "Poison Dart Frog (Dyeing)", number: 71, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Dyeing-Dart-Frog-Unavailable.webp" },
      { name: "Poison Dart Frog (Green and Black)", number: 71, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Green-Dart-Frog-Unavailable.webp" },
      { name: "Poison Dart Frog (Yellow-Banded)", number: 71, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Yellow-Dart-Frog-Unavailable.webp" },
      { name: "Blue-Fronted Amazon", number: 72, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Blue-Fronted-Amazon-Unavailable.webp" },
      { name: "Eastern Lubber Grasshopper", number: 73, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Eastern-Lubber-Unavailable.webp" },
      { name: "Rock Hyrax", number: 74, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Hyrax-Unavailable.webp" },
      { name: "Florida Red-Bellied Turtle", number: 75, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Florida-Red-Bellied-Turtle-Unavailable.webp" },
      { name: "American Black Bear", number: 76, image: "https://www.oaklandzoo.org/app/uploads/2026/03/American-Black-Bear-Unavailable.webp" },
      { name: "Dermestid Beetle", number: 77, image: "https://www.oaklandzoo.org/app/uploads/2026/03/77-of-100-Dermestid-Beetle.webp" },
      { name: "Blue-Bellied Roller", number: 78, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Blue-Bellied-Roller-Unavailable.webp" },
      { name: "Colombian Red-Tailed Boa", number: 79, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Colombian-Red-Tail-Boa-Unavailable.webp" },
      { name: "Sudan Plated Lizard", number: 80, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Sudan-Plated-Lizard-Unavailable.webp" },
      { name: "Black Beauty Walking Stick", number: 81, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Black-Beauty-Walking-Stick-Unavailable.webp" },
      { name: "Taveta Golden Weaver", number: 82, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Taveta-Golden-Weaver-Unavailable.webp" },
      { name: "Domestic Rabbit", number: 83, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Domestic-Rabbit-Unavailable.webp" },
      { name: "Hamadryas Baboon (Male)", number: 84, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Hamadryas-Baboon-m-Unavailable.webp" },
      { name: "Hamadryas Baboon (Female)", number: 84, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Hamadryas-Baboon-f-Unavailable.webp" },
      { name: "Chinese Giant Tiger Leg Centipede", number: 85, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Chinese-Tiger-Centipede-Unavailable.webp" },
      { name: "Red-Lored Amazon", number: 86, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Red-Lored-Amazon-Unavailable.webp" },
      { name: "Chuckwalla", number: 87, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Chuckwalla-Unavailable.webp" },
      { name: "Speckled Pigeon", number: 88, image: "https://www.oaklandzoo.org/app/uploads/2026/03/Speckled-Pigeon-Unavailable.webp" },
      { name: "Panamanian Golden Frog", number: 89, image: "https://www.oaklandzoo.org/app/uploads/2026/03/89-of-100-Panamanian-Golden-Frog.webp" },
      { name: "Madagascar Sacred Ibis", number: 90, image: "https://www.oaklandzoo.org/app/uploads/2026/03/90-of-100-Madagascar-Sacred-Ibis.webp" },
      { name: "Spotted Turtle", number: 91, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Spotted-Turtle-Unavailable.webp" },
      { name: "Agile Wallaby", number: 92, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Agile-Wallaby-Unavailable.webp" },
      { name: "Caribbean Cave Cockroach", number: 93, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Caribbean-Cave-Cockroach-Unavailable.webp" },
      { name: "Blue Spiny Lizard", number: 94, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Blue-Spiny-Lizard-Unavailable.webp" },
      { name: "LaMancha Goat", number: 95, image: "https://www.oaklandzoo.org/app/uploads/2026/04/LaMancha-Goat-Unavailable.webp" },
      { name: "Red-Bellied Parrot", number: 96, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Red-Bellied-Parrot-Unavailable.webp" },
      { name: "Starry Night Reed Frog", number: 97, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Starry-Night-Reed-Frog-Unavailable.webp" },
      { name: "Green Anole", number: 98, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Green-Anole-Unavailable.webp" },
      { name: "Golden Silk Orb-Weaver", number: 99, image: "https://www.oaklandzoo.org/app/uploads/2026/04/Golden-Silk-Orb-Weaver-Unavailable.webp" },
      { name: "African Lion", number: 100, image: "https://www.oaklandzoo.org/app/uploads/2026/04/African-Lion-Unavailable.webp" },
    ],
  },
  {
    id: "boo-at-the-zoo",
    name: "Boo at the Zoo",
    description: "Special edition",
    cards: [
      { name: "Lesser Flamingo" },
      { name: "White-Handed (Lar) Gibbon" },
      { name: "Chimpanzee" },
      { name: "American Alligator" },
      { name: "Caribbean Cave Cockroach" },
    ],
  },
  {
    id: "city-of-oakland",
    name: "City of Oakland",
    description: "Special edition",
    cards: [
      { name: "Black-Crowned Night Heron", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Black-crowned-night-heron-Unavailable.webp" },
      { name: "Black-Tailed Deer", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Black-tailed-Deer-Unavailable.webp" },
      { name: "California Newt", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-California-Newt-Unavailable.webp" },
      { name: "California Scrub Jay", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Special-Edition-Scrub-Jay-Unavailable.webp" },
      { name: "Common Raven", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Common-Raven-Unavailable.webp" },
      { name: "Convergent Lady Beetle", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Special-Edition-Convergent-Lady-Beetle-Unavailable.webp" },
      { name: "Coyote", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Special-Edition-Coyote.webp" },
      { name: "Eastern Fox Squirrel", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Special-Edition-Eastern-Fox-Squirrel-Unavailable.webp" },
      { name: "Mallard (Male)", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Special-Edition-Mallard-Male-Unavailable.webp" },
      { name: "Mallard (Female)", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Mallard-Female-Unavailable.webp" },
      { name: "Opossum", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Opossum-Unavailable.webp" },
      { name: "Raccoon", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Raccoon-Unavailable.webp" },
      { name: "Ring-Necked Snake", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Ring-necked-snake-Unavailable.webp" },
      { name: "Sierran Chorus Frog", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Sierran-Chorus-Frog-Unavailable.webp" },
      { name: "Western Fence Lizard", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Western-Fence-Lizard-Unavailable.webp" },
      { name: "Western Yellow Jacket", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Western-Yellowjacket-Unavailable.webp" },
      { name: "Wild Turkey", image: "https://www.oaklandzoo.org/app/uploads/2026/04/City-of-Oakland-Wild-Turkey-Unavailable.webp" },
    ],
  },
  {
    id: "coexist-with-wildlife",
    name: "Coexist with Wildlife California",
    description: "Limited series",
    cards: [
      { name: "California Grizzly Bear", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Grizzly-Bear-Unavailable.webp" },
      { name: "Desert Tortoise", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Desert-Tortoise-Unavailable.webp" },
      { name: "California Condor", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Condor-Unavailable.webp" },
      { name: "Pallid Bat", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Pallid-Bat-Unavailable.webp" },
      { name: "Whitebark Pine", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Whitebark-Pine-Unavailable.webp" },
      { name: "California Golden Trout", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Golden-Trout-Unavailable.webp" },
      { name: "Gray Wolf", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Gray-Wolf-Unavailable.webp" },
      { name: "California Tiger Salamander", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-California-Tiger-Salamander-Unavailable.webp" },
      { name: "Monarch Butterfly", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Monarch-Butterfly-Unavailable.webp" },
      { name: "Riparian Brush Rabbit", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Riparian-Brush-Rabbit-Unavailable.webp" },
      { name: "San Francisco Garter Snake", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-SF-Garter-Snake-Unavailable.webp" },
      { name: "Bakersfield Cactus", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Bakersfield-Cacust-Unavailable.webp" },
      { name: "California Black Bear", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Black-Bear-Unavailable.webp" },
      { name: "Sunflower Sea Star", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Sunflower-Sea-Star-Unavailable.webp" },
      { name: "Spotted Owl", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Spotted-Owl-Unavailable.webp" },
      { name: "Southern Sea Otter", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Southern-Sea-Otter-Unavailable.webp" },
      { name: "Blunt-Nosed Leopard Lizard", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Blunt-Nosed-Lizard-Unavailable.webp" },
      { name: "California Jewelflower", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-California-Jewelflower-Unavailable.webp" },
      { name: "Giant Kangaroo Rat", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Giant-Kangaroo-Rat-Unavailable.webp" },
      { name: "Franklin's Bumblebee", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Franklins-Bumblebee-Unavailable.webp" },
      { name: "Pacific Leatherback Sea Turtle", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Pacific-Leatherback-Unavailable.webp" },
      { name: "Island Fox", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Island-Fox-Unavailable.webp" },
      { name: "Mountain Yellow-Legged Frog", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Mountain-Yellow-Legged-Frog-Unavailable.webp" },
      { name: "Giant Black Sea Bass", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Giant-Sea-Bass-Unavailable.webp" },
      { name: "Mountain Lion", image: "https://www.oaklandzoo.org/app/uploads/2026/04/CoexistCA-Mountain-Lion-Unavailable.webp" },
    ],
  },
  {
    id: "main-entrance",
    name: "Main Entrance",
    description: "Special edition",
    cards: [
      { name: "African Spoonbill", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Special-Edition-African-Spoonbill.webp" },
      { name: "Lesser Flamingo", image: "https://www.oaklandzoo.org/app/uploads/2026/04/Special-Edition-Flamingo.webp" },
    ],
  },
  {
    id: "native-pollinators",
    name: "Native Pollinators",
    description: "Special edition",
    cards: [
      { name: "Anna's Hummingbird", image: "https://www.oaklandzoo.org/app/uploads/2026/04/6667741e6b99866b57bab603_Annas-Hummingbird-Unavailable.webp" },
      { name: "Monarch Butterfly", image: "https://www.oaklandzoo.org/app/uploads/2026/04/666778b8ecc5cc84a0f5f619_Monarch-Butterfly-Unavailable.webp" },
      { name: "Yellow-Faced Bumblebee", image: "https://www.oaklandzoo.org/app/uploads/2026/04/666778e8cbe3970293da1e97_Yellow-Faced-Bumblebee-Unavailable.webp" },
    ],
  },
  {
    id: "oakland-ballers",
    name: "Oakland Ballers",
    description: "Special edition",
    cards: [
      { name: "'Possum", image: "https://www.oaklandzoo.org/app/uploads/2026/04/66da421f0fc3c0018e483c71_Ballers-Possum-Unavailable.webp" },
    ],
  },
  {
    id: "oakland-roots-soul",
    name: "Oakland Roots & Soul",
    description: "Limited series",
    cards: [
      { name: "Black-Crowned Night Heron" },
      { name: "Silver Lupine" },
      { name: "Western Pygmy Blue" },
      { name: "Coast Live Oak" },
    ],
  },
  {
    id: "protect-the-pride",
    name: "Protect the Pride",
    description: "Limited series",
    cards: [
      { name: "African Lion", image: "https://www.oaklandzoo.org/app/uploads/2026/04/67ec3c6ea7693e28b28a5e92_Protect-the-Pride-Lion-Retired-Unavailable.webp" },
      { name: "Meerkat", image: "https://www.oaklandzoo.org/app/uploads/2026/04/67ec3c607445c1c6824f699d_Protect-the-Pride-Meerkat-Retired-Unavailable.webp" },
      { name: "Warthog", image: "https://www.oaklandzoo.org/app/uploads/2026/04/67ec3c4e39b3c1f3202c2fe8_Protect-the-Pride-Warthog-Retired-Unavailable.webp" },
    ],
  },
  {
    id: "tortugas-marinas",
    name: "Tortugas Marinas de Guatemala",
    description: "Limited series",
    cards: [
      { name: "Tortuga Parlama", image: "https://www.oaklandzoo.org/app/uploads/2026/04/TortugasdeGuatemala-Tortuga-Parlama-Unavailable.webp" },
      { name: "Tortuga Baule", image: "https://www.oaklandzoo.org/app/uploads/2026/04/TortugasdeGuatemala-Tortuga-Baule-Unavailable.webp" },
      { name: "Tortuga Verde", image: "https://www.oaklandzoo.org/app/uploads/2026/04/TortugasdeGuatemala-Tortuga-Verde-Unavailable.webp" },
      { name: "Tortuga Carey", image: "https://www.oaklandzoo.org/app/uploads/2026/04/TortugasdeGuatemala-Tortuga-Carey-Unavailable.webp" },
      { name: "Olive Ridley Sea Turtle", image: "https://www.oaklandzoo.org/app/uploads/2026/04/TortugasdeGuatemala-Olive-Ridley-Sea-Turtle-Unavailable.webp" },
    ],
  },
  {
    id: "zoocamp",
    name: "ZooCamp",
    description: "Special edition",
    cards: [
      { name: "Black-Crowned Night Heron" },
    ],
  },
];
